### ISSUE TITLE
The color is not selected on clicl

### ISSUE THREAD

**Issue by tbela99** [CBeloch/mooRainbow#1]
we need to drag to select the color. the click does nothing

**Comment by CBeloch** [comment]
I'll take a look at this soon!

**Comment by fancyoung** [comment]
simply add two lines to fix this bug:

this.overlayDrag.call(this) // add in line 202 before "this.layout.drag.start(e);"
this.sliderDrag.call(this) // add in line 277 before "this.layout.sliderDrag.start(e);"

**Comment by CBeloch** [comment]
new release out, thanks for everyone helping extending this Widget
